// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/syllables.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyllablesService_GetSyllables_FullMethodName = "/syllables.SyllablesService/GetSyllables"
)

// SyllablesServiceClient is the client API for SyllablesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyllablesServiceClient interface {
	GetSyllables(ctx context.Context, in *GetSyllablesRequest, opts ...grpc.CallOption) (*Syllables, error)
}

type syllablesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSyllablesServiceClient(cc grpc.ClientConnInterface) SyllablesServiceClient {
	return &syllablesServiceClient{cc}
}

func (c *syllablesServiceClient) GetSyllables(ctx context.Context, in *GetSyllablesRequest, opts ...grpc.CallOption) (*Syllables, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Syllables)
	err := c.cc.Invoke(ctx, SyllablesService_GetSyllables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyllablesServiceServer is the server API for SyllablesService service.
// All implementations must embed UnimplementedSyllablesServiceServer
// for forward compatibility.
type SyllablesServiceServer interface {
	GetSyllables(context.Context, *GetSyllablesRequest) (*Syllables, error)
	mustEmbedUnimplementedSyllablesServiceServer()
}

// UnimplementedSyllablesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyllablesServiceServer struct{}

func (UnimplementedSyllablesServiceServer) GetSyllables(context.Context, *GetSyllablesRequest) (*Syllables, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSyllables not implemented")
}
func (UnimplementedSyllablesServiceServer) mustEmbedUnimplementedSyllablesServiceServer() {}
func (UnimplementedSyllablesServiceServer) testEmbeddedByValue()                          {}

// UnsafeSyllablesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyllablesServiceServer will
// result in compilation errors.
type UnsafeSyllablesServiceServer interface {
	mustEmbedUnimplementedSyllablesServiceServer()
}

func RegisterSyllablesServiceServer(s grpc.ServiceRegistrar, srv SyllablesServiceServer) {
	// If the following call pancis, it indicates UnimplementedSyllablesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyllablesService_ServiceDesc, srv)
}

func _SyllablesService_GetSyllables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyllablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyllablesServiceServer).GetSyllables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyllablesService_GetSyllables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyllablesServiceServer).GetSyllables(ctx, req.(*GetSyllablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SyllablesService_ServiceDesc is the grpc.ServiceDesc for SyllablesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyllablesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "syllables.SyllablesService",
	HandlerType: (*SyllablesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSyllables",
			Handler:    _SyllablesService_GetSyllables_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/syllables.proto",
}
